apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-deployment
spec:
  selector:
    matchLabels:
      app: starbucks
  replicas: 2
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
        - name: starbucks
          image: dinu7031/starbucks:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: startbucks-service
  namespace: webapps  # Change if necessary
spec:
  type: NodePort
  selector:
    app: starbucks # This should match the labels of your pods
  ports:
    - port: 80       # Port exposed internally
      targetPort: 8080  # Port on the pod
      nodePort: 30000  # Optional: specify the node port or let Kubernetes choose one

